#!/usr/bin/env node
/**
 * status-scan.mjs · 마케팅 OS 작업 현황판 생성기 (정적 HTML 스냅샷)
 * 스캔 로직은 scripts/status-lib.mjs 공용 · 실시간 대시보드는 tools/dashboard/server.mjs
 *
 * 사용:
 *   node scripts/status-scan.mjs            # 생성 + 터미널 요약
 *   node scripts/status-scan.mjs --open     # 생성 후 브라우저 오픈
 *   node scripts/status-scan.mjs --watch 30 # 30초마다 재생성 (HTML은 자동 새로고침)
 */
import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { ROOT, ago, scanAll, scanInventory, RUNNING_WINDOW_MS } from './status-lib.mjs';

const OUT_DIR = path.join(ROOT, 'outputs', 'status');
const OUT_FILE = path.join(OUT_DIR, '작업현황판.html');
const NOW = () => new Date();
const esc = (s) => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');

function render(data) {
  const { sessions, jobs, discord, outputs, failures, git, watch, inv, calls, teams } = data;
  const now = NOW();
  const activeCount = sessions.filter(s => s.active).length;
  const dot = (on, color) => `<span class="dot ${on ? color : 'off'}"></span>`;

  const sessionRows = sessions.length ? sessions.map(s => `
    <tr><td>${dot(s.active, 'green')}${s.active ? '진행 중' : '대기'}</td>
    <td title="${esc(s.cwd)}">${esc(s.label)}</td><td>${ago(Date.now() - s.mtimeMs)}</td></tr>`).join('')
    : '<tr><td colspan="3" class="muted">최근 24시간 내 세션 없음</td></tr>';

  const jobRows = jobs.length ? jobs.map(j => `
    <tr><td>${dot(j.loaded, j.running ? 'green' : 'blue')}${j.running ? '실행 중' : j.loaded ? '대기(예약됨)' : '미등록'}</td>
    <td>${esc(j.label)}</td><td>${esc(j.schedule || '·')}</td></tr>`).join('')
    : '<tr><td colspan="3" class="muted">등록된 자동화 없음</td></tr>';

  const outputBlocks = outputs.map(g => `
    <div class="og"><div class="ogd">${g.date} <span class="muted">(${g.total}개)</span></div>
    ${g.files.map(f => `<div class="of">${esc(f.rel)} <span class="muted">${ago(Date.now() - f.mtimeMs)}</span></div>`).join('')}</div>`).join('');

  const groupCounts = {};
  for (const a of inv.agents) groupCounts[a.group] = (groupCounts[a.group] || 0) + 1;
  const groupChips = Object.entries(groupCounts).sort((x, y) => y[1] - x[1])
    .map(([g, n]) => `<span class="chip">${esc(g)} <b>${n}</b></span>`).join('');

  const agg = (list) => {
    const m = new Map();
    for (const c of list) {
      const e = m.get(c.name) || { name: c.name, count: 0, last: 0 };
      e.count++; if (c.t > e.last) e.last = c.t;
      m.set(c.name, e);
    }
    return [...m.values()].sort((x, y) => y.last - x.last);
  };
  const agentAgg = agg(calls.agentCalls);
  const skillAgg = agg(calls.skillCalls);
  const RUN_WIN = RUNNING_WINDOW_MS;

  const callRows = (list, empty) => list.length ? list.slice(0, 15).map(c => `
    <tr><td>${dot(Date.now() - c.last < RUN_WIN, 'green')}${Date.now() - c.last < RUN_WIN ? '작동 중' : '완료'}</td>
    <td><b>${esc(c.name)}</b></td><td>${c.count}회</td><td>${ago(Date.now() - c.last)}</td></tr>`).join('')
    : `<tr><td colspan="4" class="muted">${empty}</td></tr>`;

  const teamRows = teams.length ? teams.map(t => `
    <tr><td>${dot(t.active, 'green')}${t.active ? '가동 중' : '휴면'}</td>
    <td><b>${esc(t.name)}</b></td><td>${t.members.map(esc).join(', ') || '·'}</td><td>${ago(Date.now() - t.lastMs)}</td></tr>`).join('')
    : '<tr><td colspan="4" class="muted">하네스 팀 없음</td></tr>';

  const wfList = [
    ...inv.workflows.map(w => `<div class="of">🔁 ${esc(w)} <span class="muted">워크플로</span></div>`),
    ...inv.cronScripts.map(c => `<div class="of">⏰ ${esc(c)} <span class="muted">cron 스크립트</span></div>`),
  ].join('');

  const failRows = failures.length ? failures.map(f => `
    <div class="of">⚠️ <b>${esc(f.job || '?')}</b> exit ${f.exit_code} · ${esc((f.ts || '').slice(0, 16).replace('T', ' '))}
    <div class="muted small">${esc((f.stderr_tail || '').slice(0, 120))}</div></div>`).join('')
    : '<div class="muted">최근 실패 기록 없음 ✅</div>';

  return `<!-- generated by scripts/status-scan.mjs -->
<meta charset="utf-8">
${watch ? `<meta http-equiv="refresh" content="${watch}">` : ''}
<title>마케팅 OS 작업 현황판</title>
<style>
  :root { --bg:#f7f7f8; --card:#fff; --fg:#1a1a1e; --muted:#8a8a93; --line:#e8e8ec; --accent:#4f6ef7; }
  @media (prefers-color-scheme: dark) { :root { --bg:#141417; --card:#1e1e23; --fg:#ececf1; --muted:#8a8a93; --line:#2c2c33; } }
  * { box-sizing:border-box; margin:0; }
  body { background:var(--bg); color:var(--fg); font-family:-apple-system,'Apple SD Gothic Neo',sans-serif; padding:32px 20px; }
  .wrap { max-width:880px; margin:0 auto; }
  h1 { font-size:22px; margin-bottom:4px; }
  .sub { color:var(--muted); font-size:13px; margin-bottom:24px; }
  .grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(160px,1fr)); gap:12px; margin-bottom:24px; }
  .kpi { background:var(--card); border:1px solid var(--line); border-radius:12px; padding:16px; }
  .kpi .n { font-size:26px; font-weight:700; }
  .kpi .l { font-size:12px; color:var(--muted); margin-top:4px; }
  .card { background:var(--card); border:1px solid var(--line); border-radius:12px; padding:18px 20px; margin-bottom:16px; }
  .card h2 { font-size:14px; margin-bottom:12px; color:var(--accent); }
  table { width:100%; border-collapse:collapse; font-size:13px; }
  td { padding:7px 8px 7px 0; border-top:1px solid var(--line); vertical-align:top; }
  tr:first-child td { border-top:none; }
  .dot { display:inline-block; width:8px; height:8px; border-radius:50%; margin-right:7px; }
  .dot.green { background:#2ecc71; box-shadow:0 0 6px #2ecc7188; }
  .dot.blue { background:#4f6ef7; }
  .dot.off { background:#555; opacity:.4; }
  .muted { color:var(--muted); }
  .small { font-size:11px; }
  .og { margin-bottom:10px; } .ogd { font-weight:600; font-size:13px; margin-bottom:4px; }
  .of { font-size:12.5px; padding:3px 0 3px 12px; overflow-wrap:anywhere; }
  .chip { display:inline-block; background:var(--bg); border:1px solid var(--line); border-radius:20px; padding:3px 10px; font-size:12px; margin:2px 4px 2px 0; }
</style>
<div class="wrap">
  <h1>🖥️ 마케팅 OS 작업 현황판</h1>
  <div class="sub">${now.toLocaleString('ko-KR')} 스캔 · ${watch ? `${watch}초마다 자동 갱신` : '수동 갱신: node scripts/status-scan.mjs'} · 실시간 대시보드: npm run dashboard</div>
  <div class="grid">
    <div class="kpi"><div class="n">${activeCount}</div><div class="l">🟢 지금 작동 중인 세션</div></div>
    <div class="kpi"><div class="n">${sessions.length}</div><div class="l">최근 24시간 작업 세션</div></div>
    <div class="kpi"><div class="n">${jobs.filter(j => j.loaded).length}/${jobs.length}</div><div class="l">자동화 예약 가동</div></div>
    <div class="kpi"><div class="n">${discord.count > 0 ? 'ON' : 'OFF'}</div><div class="l">트루먼 디스코드 브리지${discord.count > 3 ? ` (프로세스 ${discord.count}개 · 정리 권장)` : ''}</div></div>
    <div class="kpi"><div class="n">${calls.agentCalls.length}</div><div class="l">에이전트 호출 (24시간)</div></div>
    <div class="kpi"><div class="n">${calls.skillCalls.length}</div><div class="l">스킬 호출 (24시간)</div></div>
  </div>
  <div class="card"><h2>Claude Code 세션 (최근 24시간)</h2><table>${sessionRows}</table></div>
  <div class="card"><h2>에이전트 작동 기록 (최근 24시간 · marketing-os 세션 기준)</h2><table>${callRows(agentAgg, '최근 24시간 내 에이전트 호출 없음')}</table></div>
  <div class="card"><h2>하네스 팀 (에이전트 팀 모드)</h2><table>${teamRows}</table></div>
  <div class="card"><h2>스킬 작동 기록 (최근 24시간)</h2><table>${callRows(skillAgg, '최근 24시간 내 스킬 호출 없음')}</table></div>
  <div class="card"><h2>보유 자산 인벤토리</h2>
    <div style="margin-bottom:8px">🤖 에이전트 <b>${inv.agents.length}</b>개 · 🧩 스킬 <b>${inv.skills.length}</b>개 · ⌨️ 커맨드 <b>${inv.commands.length}</b>개 · 🔌 MCP <b>${inv.mcp.length}</b>개 · 🔁 워크플로 <b>${inv.workflows.length + inv.cronScripts.length}</b>개</div>
    <div>${groupChips}</div></div>
  <div class="card"><h2>워크플로·cron 정의</h2>${wfList || '<div class="muted">없음</div>'}</div>
  <div class="card"><h2>자동화 (launchd 예약 작업)</h2><table>${jobRows}</table>
    <div class="muted small" style="margin-top:8px">클라우드 루틴은 별도 · 터미널에서 "루틴 목록 보여줘"로 확인</div></div>
  <div class="card"><h2>최근 산출물 (outputs/)</h2>${outputBlocks || '<div class="muted">없음</div>'}</div>
  <div class="card"><h2>실패 로그 (logs/failures.jsonl)</h2>${failRows}</div>
  <div class="card"><h2>git 작업 중 변경사항</h2>
    <div>${git.changed}개 파일 변경됨</div>
    ${git.sample.map(s => `<div class="of muted">${esc(s)}</div>`).join('')}</div>
</div>`;
}

const args = process.argv.slice(2);
const watchIdx = args.indexOf('--watch');
const watchSec = watchIdx >= 0 ? parseInt(args[watchIdx + 1] || '30', 10) : 0;

function runOnce() {
  const data = { ...scanAll(), inv: scanInventory(), watch: watchSec };
  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(OUT_FILE, render(data));
  const active = data.sessions.filter(s => s.active);
  const runningAgents = [...new Set(data.calls.agentCalls.filter(c => Date.now() - c.t < 15 * 60000).map(c => c.name))];
  console.log(`✅ 현황판 갱신 · ${NOW().toLocaleTimeString('ko-KR')}`);
  console.log(`   🟢 작동 중 세션 ${active.length}개${active.length ? ' · ' + active.map(s => s.label).join(', ') : ''}`);
  console.log(`   🤖 에이전트 호출 24h ${data.calls.agentCalls.length}건${runningAgents.length ? ' · 작동 중: ' + runningAgents.join(', ') : ''} · 스킬 호출 ${data.calls.skillCalls.length}건`);
  console.log(`   👥 하네스 팀 ${data.teams.length}개 (가동 중 ${data.teams.filter(t => t.active).length}개) · 인벤토리: 에이전트 ${data.inv.agents.length} · 스킬 ${data.inv.skills.length} · 커맨드 ${data.inv.commands.length} · MCP ${data.inv.mcp.length}`);
  console.log(`   ⏰ 자동화 ${data.jobs.filter(j => j.loaded).length}/${data.jobs.length} 예약 가동 · 트루먼 브리지 ${data.discord.count > 0 ? 'ON' : 'OFF'}`);
  console.log(`   📄 ${OUT_FILE}`);
  return data;
}

runOnce();
if (args.includes('--open')) { try { execSync(`open "${OUT_FILE}"`); } catch {} }
if (watchSec > 0) {
  console.log(`👀 ${watchSec}초마다 재스캔 중 (Ctrl+C로 종료)`);
  setInterval(runOnce, watchSec * 1000);
}
